title: NadirLabs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
      
url: https://nadirlabs.xyz

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: G-9Q5ZQG39Y2
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

aux_links:
  GitHub: https://github.com/eadali
